[workspace]
resolver = "3"
members = [
  "authentication",
  "client",
  "dev-client",
  "node",
  "test-utils",
]

[workspace.package]
edition = "2024"
rust-version = "1.91"
readme = "./README.md"
homepage = "https://www.taceo.io"
repository = "https://github.com/TaceoLabs/zkpassport-OPRF"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
alloy = { version = "2", default-features = false }
ark-babyjubjub = { package = "taceo-ark-babyjubjub", version = "0.5.3" }
ark-ff = "0.5"
ark-serialize = "0.5"
# Pin axum to 0.8.8 to avoid pulling in tungstenite 0.29, which conflicts with the tungstenite version used by taceo_oprf upstream. The version mismatch breaks downcast_ref, causing errors to be misclassified.
axum = "=0.8.9"
backon = { version = "1.6", default-features = false }
clap = "4"
config = { version = "0.15", default-features = false }
eyre = { version = "0.6" }
humantime-serde = "1.1.1"
metrics = "0.24"
rand = { version = "0.8" }
reqwest = { version = "0.13", default-features = false }
ruint = "1.18.0"
rustls = "0.23"
serde = { version = "1" }
serde_json = { version = "1" }
taceo-nodes-common = { version = "0.7.4", default-features = false }
taceo-oprf = { version = "0.17.2", default-features = false }
telemetry-batteries = { version = "0.2.1", default-features = false }
testcontainers = { version = "0.27", features = [
  "host-port-exposure",
  "http_wait_plain"
] }
thiserror = { version = "2" }
tikv-jemallocator = "0.7"
tokio = { version = "1" }
tokio-util = "0.7"
tower-http = { version = "=0.6.10", default-features = false }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
url = { version = "2", default-features = false }
uuid = { version = "1" }

[profile.release]
lto = true
codegen-units = 1

# This profile can be used for CI in pull requests.
[profile.ci-dev]
inherits = "dev"
opt-level = 1
debug = true
incremental = false

[profile.profiling]
inherits = "bench"
debug = true
lto = "thin"
