[package]
name = "taceo-zkpassport-oprf-node"
version = "1.0.0"
edition.workspace = true
rust-version.workspace = true
description = "Backend server for zkPassport instance of TACEO:OPRF"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["cryptography", "mpc", "oprf"]
publish = ["github-only"]

[dependencies]
ark-serialize.workspace = true
axum = { workspace = true }
backon = { workspace = true, features = ["std", "tokio-sleep"] }
config = { workspace = true }
eyre.workspace = true
humantime-serde.workspace = true
metrics = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
rustls = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
taceo-nodes-common = { workspace = true, features = ["postgres"] }
taceo-oprf = { workspace = true, features = ["postgres", "service"] }
telemetry-batteries = { workspace = true, features = ["metrics-statsd"] }
thiserror.workspace = true
tokio = { workspace = true, features = [
  "net",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
  "tokio-macros",
] }
tokio-util.workspace = true
tower-http = { workspace = true, features = ["catch-panic"] }
tracing = { workspace = true, features = ["release_max_level_debug"] }
url = { workspace = true, features = ["serde"] }
zkpassport-oprf-authentication = { package = "taceo-zkpassport-oprf-authentication", path = "../authentication", version = "0.1" }

[dev-dependencies]
ruint.workspace = true
taceo-oprf = { workspace = true, features = ["core", "postgres", "service"] }
uuid = { workspace = true, features = ["serde", "v4"] }
zkpassport-oprf-test-utils = { package = "taceo-zkpassport-oprf-test-utils", path = "../test-utils", version = "0.1", features = [
  "containers"
] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator.workspace = true
