[package]
name = "taceo-zkpassport-oprf-node"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Backend server for zkPassport instance of TACEO:OPRF"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["cryptography", "mpc", "oprf"]
publish.workspace = true

[dependencies]
ark-serialize.workspace = true
axum = { workspace = true }
config = { workspace = true }
eyre.workspace = true
humantime-serde.workspace = true
metrics = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
taceo-nodes-common = { workspace = true, features = ["postgres"] }
taceo-oprf = { workspace = true, features = ["service"] }
telemetry-batteries = { workspace = true, features = ["metrics-statsd"] }
thiserror.workspace = true
tokio = { workspace = true, features = [
  "net",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
  "tokio-macros",
] }
tokio-util.workspace = true
tracing = { workspace = true, features = ["release_max_level_debug"] }
zkpassport-oprf-authentication = { package = "taceo-zkpassport-oprf-authentication", path = "../authentication", version = "0.1" }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator.workspace = true
